backtest:
  commission: 0.0002
  initial_cash: 100000
ctp:
  app_id: client_wtyj_1.0.9.9
  auth_code: VCSX4A2S43I4RN25
  broker_id: '3070'
  fronts:
    telecom:
      md_address: tcp://101.230.79.235:32213
      td_address: tcp://101.230.79.235:32205
  interface_product_info: wtpy
  investor_id: '333306116'
  password: '199057'
  user_id: '333306116'
  user_product_info: wtpy
data:
  asset_type: forex
  category: 外汇
  data_type: stock
  directory_path: /Users/yunjinqi/Documents/new_projects/backtrader_web/datas/forex
  end_date: '2026-04-09T23:35:02+00:00'
  range_type: date
  start_date: '2020-01-01T00:00:00+00:00'
  symbol: AAON
  symbol_name: AAON
  timeframe: 1d
  timeframe_n: 1
  use_end_date: true
live:
  bar_seconds: 60
  contract_metadata:
    rb2504:
      max_order_size: 1
      min_price_tick: 1.0
  duration_seconds: 3600
  max_order_size: 1
  min_price_tick: 1.0
  network: telecom
  session_timeout: 3700
  symbol: rb2504
optimization_config:
  artifact_root: /Users/yunjinqi/Documents/new_projects/backtrader_web/workspace_units/5e5ca26f-dbc6-47cd-9016-20c3024cdc51/cf21f16e-c9ad-4035-badf-e8322fdff02c/optimization_runs/ba631d5a-0f08-470b-9eb4-128325e1b8a9
  max_display: 5000
  mode: grid
  n_workers: 4
  objective: sharpe_max
  param_layers:
  - current_value: 5
    end: 20
    opt_type: equal_diff
    param_name: fast_period
    start: 5
    step: 5
  - current_value: 21
    end: 60
    opt_type: equal_diff
    param_name: slow_period
    start: 20
    step: 10
  - current_value: 10
    end: 10
    opt_type: equal_diff
    param_name: stake
    start: 10
    step: 10
  param_ranges:
    fast_period:
      end: 20.0
      start: 5.0
      step: 5.0
      type: int
    slow_period:
      end: 60.0
      start: 20.0
      step: 10.0
      type: int
  submitted_at: '2026-04-11T01:53:29.271671+00:00'
  timeout: 0
params:
  fast_period: 10
  slow_period: 20
  stake: 10
strategy:
  author: Backtrader Strategies Compendium
  description: 使用快速和慢速双指数移动平均线(DEMA)交叉产生交易信号的趋势跟踪策略，金叉买入死叉卖出
  name: DEMA双均线-AAON
unit_settings:
  commission: 0.0002
  initial_cash: 100000
workspace_unit:
  asset_type: forex
  data_root: /Users/yunjinqi/Documents/new_projects/backtrader_web/datas
  data_source_type: csv
  group_name: 黄金工作区-双均线日线组
  strategy_id: backtest/097_dema_crossover
  strategy_module: strategy_dema_crossover.py
  strategy_name: DEMA双均线-AAON
  template_dir: /Users/yunjinqi/Documents/new_projects/backtrader_web/strategies/backtest/097_dema_crossover
  unit_id: cf21f16e-c9ad-4035-badf-e8322fdff02c
  workspace_id: 5e5ca26f-dbc6-47cd-9016-20c3024cdc51
