"""Citation-level verification for public asset-research reports.

The report is allowed to be generated by an LLM only after this module proves
that every section carries a known evidence ID and that the rendered payload
does not expose candidate-only fields.  The verifier is deterministic and
never trusts LLM self-reports.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass

from app.schemas.asset_research import ReportSection

_CANDIDATE_ONLY_KEYS = {
    "candidate_decision",
    "candidate_decision_json",
    "confidence",
    "prediction_heads",
    "probabilities",
    "expected_net_utility",
}


@dataclass(frozen=True, slots=True)
class CitationVerification:
    """One machine-readable citation verdict for a public report."""

    passed: bool
    missing_evidence_ids: tuple[str, ...]
    invalid_evidence_ids: tuple[str, ...]
    sections_without_evidence: tuple[str, ...]
    candidate_fields_exposed: tuple[str, ...]


def verify_section_citations(
    sections: Sequence[ReportSection],
    *,
    allowed_evidence_ids: Iterable[str],
) -> CitationVerification:
    """Return whether all report sections cite known evidence IDs."""
    allowed = set(allowed_evidence_ids)
    missing: list[str] = []
    no_evidence: list[str] = []
    for section in sections:
        if not section.evidence_ids:
            no_evidence.append(section.section_id)
            continue
        missing.extend(
            evidence_id for evidence_id in section.evidence_ids if evidence_id not in allowed
        )
    # Preserve deterministic order for audits.
    missing_ordered = tuple(sorted(set(missing)))
    invalid_ordered = tuple(
        evidence_id
        for evidence_id in missing_ordered
        if not isinstance(evidence_id, str) or not evidence_id
    )
    passed = not missing_ordered and not no_evidence
    return CitationVerification(
        passed=passed,
        missing_evidence_ids=missing_ordered,
        invalid_evidence_ids=invalid_ordered,
        sections_without_evidence=tuple(no_evidence),
        candidate_fields_exposed=(),
    )


def verify_public_payload(payload: Mapping[str, object]) -> CitationVerification:
    """Verify the rendered report payload does not expose candidate-only fields."""
    sections = payload.get("sections")
    allowed_evidence = _allowed_evidence_from_payload(payload)
    if not isinstance(sections, Sequence) or isinstance(sections, (str, bytes)):
        return CitationVerification(
            passed=False,
            missing_evidence_ids=(),
            invalid_evidence_ids=(),
            sections_without_evidence=("payload",),
            candidate_fields_exposed=tuple(_exposed_candidate_keys(payload)),
        )
    normalized_sections = [
        ReportSection.model_validate(section)
        for section in sections
        if isinstance(section, Mapping)
    ]
    section_verification = verify_section_citations(
        normalized_sections,
        allowed_evidence_ids=allowed_evidence,
    )
    candidate_fields = tuple(_exposed_candidate_keys(payload))
    return CitationVerification(
        passed=section_verification.passed and not candidate_fields,
        missing_evidence_ids=section_verification.missing_evidence_ids,
        invalid_evidence_ids=section_verification.invalid_evidence_ids,
        sections_without_evidence=section_verification.sections_without_evidence,
        candidate_fields_exposed=candidate_fields,
    )


def _allowed_evidence_from_payload(payload: Mapping[str, object]) -> set[str]:
    """Collect evidence IDs from all public sections, not from the LLM text."""
    allowed: set[str] = set()
    sections = payload.get("sections")
    if not isinstance(sections, Sequence):
        return allowed
    for section in sections:
        if not isinstance(section, Mapping):
            continue
        evidence_ids = section.get("evidence_ids")
        if isinstance(evidence_ids, list):
            allowed.update(str(value) for value in evidence_ids if isinstance(value, str))
    return allowed


def _exposed_candidate_keys(payload: Mapping[str, object]) -> list[str]:
    """Recursively find candidate-only keys in a serialized public payload."""
    exposed: list[str] = []

    def visit(value: object) -> None:
        if isinstance(value, Mapping):
            for key, nested in value.items():
                if (
                    isinstance(key, str)
                    and key in _CANDIDATE_ONLY_KEYS
                    and nested not in (None, [], {})
                ):
                    exposed.append(key)
                visit(nested)
        elif isinstance(value, list):
            for item in value:
                visit(item)

    visit(payload)
    return sorted(set(exposed))
