from typing import Any

import sqlalchemy as sa

from alembic import op

# alembic-meta: estimated_rows=1000000; lock_kind=long
revision = "21d572b67d8e"
down_revision = "20260718_runtime_identity_lifecycle"
branch_labels = None
depends_on = None


def _table_exists(table_name: str) -> bool:
    return table_name in sa.inspect(op.get_bind()).get_table_names()


def _column_exists(table_name: str, column_name: str) -> bool:
    return any(
        column["name"] == column_name
        for column in sa.inspect(op.get_bind()).get_columns(table_name)
    )


def _index_exists(table_name: str, index_name: str) -> bool:
    return any(
        index["name"] == index_name for index in sa.inspect(op.get_bind()).get_indexes(table_name)
    )


def _foreign_key_exists(
    table_name: str,
    local_columns: list[str],
    referred_table: str,
    referred_columns: list[str],
) -> bool:
    return any(
        foreign_key.get("constrained_columns") == local_columns
        and foreign_key.get("referred_table") == referred_table
        and foreign_key.get("referred_columns") == referred_columns
        for foreign_key in sa.inspect(op.get_bind()).get_foreign_keys(table_name)
    )


class _SchemaAwareOperations:
    """Avoid replaying generated DDL over legacy ``create_all`` databases."""

    def __init__(self, operations: Any) -> None:
        self._operations = operations

    def __getattr__(self, name: str) -> Any:
        return getattr(self._operations, name)

    def create_table(self, table_name: str, *columns: Any, **kwargs: Any) -> Any:
        if _table_exists(table_name):
            return None
        return self._operations.create_table(table_name, *columns, **kwargs)

    def create_index(self, index_name: str, table_name: str, columns: Any, **kwargs: Any) -> Any:
        if _index_exists(table_name, str(index_name)):
            return None
        return self._operations.create_index(index_name, table_name, columns, **kwargs)

    def drop_index(self, index_name: str, table_name: str | None = None, **kwargs: Any) -> Any:
        if table_name is not None and not _index_exists(table_name, str(index_name)):
            return None
        return self._operations.drop_index(index_name, table_name=table_name, **kwargs)

    def add_column(self, table_name: str, column: Any, **kwargs: Any) -> Any:
        if _column_exists(table_name, column.name):
            return None
        return self._operations.add_column(table_name, column, **kwargs)

    def create_foreign_key(
        self,
        constraint_name: str | None,
        source_table: str,
        referent_table: str,
        local_columns: list[str],
        remote_columns: list[str],
        **kwargs: Any,
    ) -> Any:
        if _foreign_key_exists(source_table, local_columns, referent_table, remote_columns):
            return None
        return self._operations.create_foreign_key(
            constraint_name,
            source_table,
            referent_table,
            local_columns,
            remote_columns,
            **kwargs,
        )


def _is_sqlite() -> bool:
    return op.get_bind().dialect.name == "sqlite"


def upgrade() -> None:
    global op
    op = _SchemaAwareOperations(op)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "broker_connection_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("broker_id", sa.String(length=50), nullable=False),
        sa.Column("account_alias", sa.String(length=100), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("credentials_ref", sa.JSON(), nullable=False),
        sa.Column("runtime_gateway_key", sa.String(length=120), nullable=True),
        sa.Column("runtime_account_id", sa.String(length=100), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_health", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("is_destructive_enabled", sa.Boolean(), nullable=False),
        sa.Column("credentials_rotated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "created_by",
            "broker_id",
            "account_alias",
            name="uq_broker_connection_profiles_owner_alias",
        ),
    )
    op.create_index(
        op.f("ix_broker_connection_profiles_broker_id"),
        "broker_connection_profiles",
        ["broker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_broker_connection_profiles_created_by"),
        "broker_connection_profiles",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        "ix_broker_connection_profiles_enabled",
        "broker_connection_profiles",
        ["enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_broker_connection_profiles_runtime_gateway_key"),
        "broker_connection_profiles",
        ["runtime_gateway_key"],
        unique=False,
    )
    op.create_table(
        "dg_providers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("auth_type", sa.String(length=50), nullable=False),
        sa.Column("api_key_env", sa.String(length=100), nullable=True),
        sa.Column("rate_limit", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dg_providers_category"), "dg_providers", ["category"], unique=False)
    op.create_index(
        op.f("ix_dg_providers_provider_id"), "dg_providers", ["provider_id"], unique=True
    )
    op.create_table(
        "strategy_explanations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("indicators_explanation", sa.Text(), nullable=False),
        sa.Column("entry_explanation", sa.Text(), nullable=False),
        sa.Column("exit_explanation", sa.Text(), nullable=False),
        sa.Column("params_explanation", sa.Text(), nullable=False),
        sa.Column("market_fit", sa.Text(), nullable=False),
        sa.Column("risk_notes", sa.JSON(), nullable=True),
        sa.Column("ast_payload", sa.JSON(), nullable=True),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("model_id", sa.String(length=128), nullable=True),
        sa.Column("disclaimer", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategy_explanations_code_hash"),
        "strategy_explanations",
        ["code_hash"],
        unique=True,
    )
    op.create_table(
        "audit_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_target", sa.String(length=200), nullable=True),
        sa.Column("page_path", sa.String(length=500), nullable=False),
        sa.Column("event_data", sa.Text(), nullable=True),
        sa.Column("client_timestamp", sa.DateTime(), nullable=False),
        sa.Column("server_timestamp", sa.DateTime(), nullable=False),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_records_event_type"), "audit_records", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_records_session_id"), "audit_records", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_audit_records_user_id"), "audit_records", ["user_id"], unique=False)
    op.create_index(
        "ix_audit_server_timestamp", "audit_records", ["server_timestamp"], unique=False
    )
    op.create_index(
        "ix_audit_user_timestamp", "audit_records", ["user_id", "server_timestamp"], unique=False
    )
    op.create_table(
        "dg_endpoints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider_id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("function_path", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("params_schema", sa.JSON(), nullable=False),
        sa.Column("auth_type", sa.String(length=50), nullable=False),
        sa.Column("api_key_env", sa.String(length=100), nullable=True),
        sa.Column("rate_limit", sa.Integer(), nullable=False),
        sa.Column("cache_ttl_sec", sa.Integer(), nullable=False),
        sa.Column("target_database", sa.String(length=100), nullable=False),
        sa.Column("target_table", sa.String(length=100), nullable=True),
        sa.Column("normalization_profile", sa.JSON(), nullable=False),
        sa.Column("quality_profile", sa.JSON(), nullable=False),
        sa.Column("incremental_sync_key", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("legacy_interface_name", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["dg_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "endpoint_name", name="uq_dg_endpoint_provider_name"),
    )
    op.create_index(op.f("ix_dg_endpoints_category"), "dg_endpoints", ["category"], unique=False)
    op.create_index(
        op.f("ix_dg_endpoints_endpoint_name"), "dg_endpoints", ["endpoint_name"], unique=False
    )
    op.create_index(
        op.f("ix_dg_endpoints_legacy_interface_name"),
        "dg_endpoints",
        ["legacy_interface_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dg_endpoints_provider_id"), "dg_endpoints", ["provider_id"], unique=False
    )
    op.create_table(
        "news_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "name", name="uq_news_sources_owner_name"),
    )
    op.create_index(op.f("ix_news_sources_owner_id"), "news_sources", ["owner_id"], unique=False)
    op.create_table(
        "portfolio_ledgers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_currency", sa.String(length=20), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("benchmark_symbol", sa.String(length=50), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_ledgers_owner_id"), "portfolio_ledgers", ["owner_id"], unique=False
    )
    op.create_table(
        "dg_endpoint_params",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("param_type", sa.String(length=50), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("default_value", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["dg_endpoints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dg_endpoint_params_endpoint_id"),
        "dg_endpoint_params",
        ["endpoint_id"],
        unique=False,
    )
    op.create_table(
        "dg_ingest_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "RUNNING", "COMPLETED", "FAILED", name="dgjobstatus"),
            nullable=False,
        ),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["dg_endpoints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dg_ingest_jobs_endpoint_id"), "dg_ingest_jobs", ["endpoint_id"], unique=False
    )
    op.create_index(
        op.f("ix_dg_ingest_jobs_idempotency_key"),
        "dg_ingest_jobs",
        ["idempotency_key"],
        unique=False,
    )
    op.create_table(
        "dg_quality_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("endpoint_id", sa.String(length=36), nullable=False),
        sa.Column("rule_name", sa.String(length=100), nullable=False),
        sa.Column("rule_type", sa.String(length=50), nullable=False),
        sa.Column("rule_config", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["dg_endpoints.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dg_quality_rules_endpoint_id"), "dg_quality_rules", ["endpoint_id"], unique=False
    )
    op.create_table(
        "news_articles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("headline", sa.String(length=1000), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("canonical_url", sa.String(length=512), nullable=False),
        sa.Column("tickers", sa.JSON(), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("source_flag", sa.String(length=30), nullable=False),
        sa.Column("sentiment", sa.String(length=20), nullable=False),
        sa.Column("impact", sa.String(length=20), nullable=False),
        sa.Column("threat", sa.String(length=20), nullable=False),
        sa.Column("cluster_id", sa.String(length=36), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["source_id"], ["news_sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id", "canonical_url", name="uq_news_articles_owner_canonical_url"
        ),
    )
    op.create_index(
        op.f("ix_news_articles_canonical_url"), "news_articles", ["canonical_url"], unique=False
    )
    op.create_index(
        op.f("ix_news_articles_cluster_id"), "news_articles", ["cluster_id"], unique=False
    )
    op.create_index(op.f("ix_news_articles_owner_id"), "news_articles", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_news_articles_source_id"), "news_articles", ["source_id"], unique=False
    )
    op.create_table(
        "portfolio_ledger_imports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("portfolio_id", sa.String(length=36), nullable=False),
        sa.Column("import_format", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("imported_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolio_ledgers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "portfolio_id",
            "idempotency_key",
            name="uq_portfolio_ledger_imports_portfolio_idempotency",
        ),
    )
    op.create_index(
        op.f("ix_portfolio_ledger_imports_idempotency_key"),
        "portfolio_ledger_imports",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_ledger_imports_portfolio_id"),
        "portfolio_ledger_imports",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "portfolio_ledger_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("portfolio_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_date", sa.String(length=20), nullable=False),
        sa.Column("snapshot_index", sa.Integer(), nullable=False),
        sa.Column("cash_flow", sa.Float(), nullable=False),
        sa.Column("nav", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolio_ledgers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "portfolio_id",
            "snapshot_date",
            "snapshot_index",
            name="uq_portfolio_ledger_snapshots_portfolio_date_index",
        ),
    )
    op.create_index(
        op.f("ix_portfolio_ledger_snapshots_portfolio_id"),
        "portfolio_ledger_snapshots",
        ["portfolio_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_ledger_snapshots_snapshot_date"),
        "portfolio_ledger_snapshots",
        ["snapshot_date"],
        unique=False,
    )
    op.create_table(
        "portfolio_ledger_transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("portfolio_id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("trade_type", sa.String(length=30), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("trade_date", sa.String(length=20), nullable=False),
        sa.Column("benchmark_symbol", sa.String(length=50), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolio_ledgers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_ledger_transactions_portfolio_id"),
        "portfolio_ledger_transactions",
        ["portfolio_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_ledger_transactions_trade_date"),
        "portfolio_ledger_transactions",
        ["trade_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_ledger_transactions_trade_type"),
        "portfolio_ledger_transactions",
        ["trade_type"],
        unique=False,
    )
    op.create_table(
        "news_analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("article_id", sa.String(length=36), nullable=True),
        sa.Column("headline", sa.String(length=1000), nullable=False),
        sa.Column("sentiment", sa.String(length=20), nullable=False),
        sa.Column("impact", sa.String(length=20), nullable=False),
        sa.Column("threat", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["news_articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_news_analyses_article_id"), "news_analyses", ["article_id"], unique=False
    )
    op.create_index(op.f("ix_news_analyses_owner_id"), "news_analyses", ["owner_id"], unique=False)
    op.create_table(
        "overfitting_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("backtest_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_methods", sa.JSON(), nullable=True),
        sa.Column("overall_level", sa.String(length=16), nullable=False),
        sa.Column("robustness_score", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("methods", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["backtest_id"],
            ["backtest_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_overfitting_results_backtest_id"),
        "overfitting_results",
        ["backtest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_overfitting_results_task_id"), "overfitting_results", ["task_id"], unique=True
    )
    op.create_index(
        op.f("ix_overfitting_results_user_id"), "overfitting_results", ["user_id"], unique=False
    )
    op.create_table(
        "strategy_scores",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("backtest_id", sa.String(length=36), nullable=True),
        sa.Column("total_score", sa.Float(), nullable=True),
        sa.Column("level", sa.String(length=5), nullable=True),
        sa.Column("model_version", sa.String(length=32), nullable=True),
        sa.Column("disclaimer", sa.Text(), nullable=False),
        sa.Column("dimensions", sa.JSON(), nullable=True),
        sa.Column("weights", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["backtest_id"],
            ["backtest_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategy_scores_backtest_id"), "strategy_scores", ["backtest_id"], unique=True
    )
    op.create_index(
        op.f("ix_ai_strategy_research_version_comparisons_created_at"),
        "ai_strategy_research_version_comparisons",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_strategy_research_version_comparisons_left_version_id"),
        "ai_strategy_research_version_comparisons",
        ["left_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_strategy_research_version_comparisons_right_version_id"),
        "ai_strategy_research_version_comparisons",
        ["right_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_strategy_research_version_comparisons_user_id"),
        "ai_strategy_research_version_comparisons",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_strategy_research_versions_backtest_task_id"),
        "ai_strategy_research_versions",
        ["backtest_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_strategy_research_versions_mandate_id"),
        "ai_strategy_research_versions",
        ["mandate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_strategy_research_versions_quality_gate_status"),
        "ai_strategy_research_versions",
        ["quality_gate_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_strategy_research_versions_strategy_id"),
        "ai_strategy_research_versions",
        ["strategy_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_strategy_research_versions_unit_id"),
        "ai_strategy_research_versions",
        ["unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_strategy_research_versions_user_id"),
        "ai_strategy_research_versions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_strategy_research_versions_workspace_id"),
        "ai_strategy_research_versions",
        ["workspace_id"],
        unique=False,
    )
    op.add_column(
        "ak_task_executions", sa.Column("airflow_dag_id", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "ak_task_executions", sa.Column("airflow_run_id", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "ak_task_executions", sa.Column("airflow_task_id", sa.String(length=200), nullable=True)
    )
    op.create_index(
        op.f("ix_ak_task_executions_airflow_dag_id"),
        "ak_task_executions",
        ["airflow_dag_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ak_task_executions_airflow_run_id"),
        "ak_task_executions",
        ["airflow_run_id"],
        unique=False,
    )
    needs_unit_foreign_key = not _foreign_key_exists(
        "alerts", ["unit_id"], "strategy_units", ["id"]
    )
    needs_workspace_foreign_key = not _foreign_key_exists(
        "alerts", ["workspace_id"], "workspaces", ["id"]
    )
    if needs_unit_foreign_key or needs_workspace_foreign_key:
        if _is_sqlite():
            with op.batch_alter_table("alerts") as batch_op:
                if needs_unit_foreign_key:
                    batch_op.create_foreign_key(
                        "fk_alerts_unit_id_strategy_units",
                        "strategy_units",
                        ["unit_id"],
                        ["id"],
                    )
                if needs_workspace_foreign_key:
                    batch_op.create_foreign_key(
                        "fk_alerts_workspace_id_workspaces",
                        "workspaces",
                        ["workspace_id"],
                        ["id"],
                    )
        else:
            if needs_unit_foreign_key:
                op.create_foreign_key(
                    "fk_alerts_unit_id_strategy_units",
                    "alerts",
                    "strategy_units",
                    ["unit_id"],
                    ["id"],
                )
            if needs_workspace_foreign_key:
                op.create_foreign_key(
                    "fk_alerts_workspace_id_workspaces",
                    "alerts",
                    "workspaces",
                    ["workspace_id"],
                    ["id"],
                )
    op.create_index(op.f("ix_alerts_instance_id"), "alerts", ["instance_id"], unique=False)
    op.create_index(op.f("ix_alerts_unit_id"), "alerts", ["unit_id"], unique=False)
    op.create_index(op.f("ix_alerts_workspace_id"), "alerts", ["workspace_id"], unique=False)
    op.drop_index(op.f("idx_backtest_tasks_status"), table_name="backtest_tasks")
    op.drop_index(op.f("idx_backtest_tasks_user_created_at"), table_name="backtest_tasks")
    op.drop_index(op.f("idx_backtest_tasks_user_status"), table_name="backtest_tasks")
    op.drop_index(op.f("idx_backtest_tasks_version_status_created_at"), table_name="backtest_tasks")
    if _is_sqlite():
        with op.batch_alter_table("chat_conversations") as batch_op:
            batch_op.alter_column(
                "knowledge_base_id", existing_type=sa.VARCHAR(length=36), nullable=True
            )
    else:
        op.alter_column(
            "chat_conversations",
            "knowledge_base_id",
            existing_type=sa.VARCHAR(length=36),
            nullable=True,
        )
    op.add_column("chat_messages", sa.Column("metadata", sa.JSON(), nullable=True))
    op.create_index(
        op.f("ix_live_handoff_reviews_decision"), "live_handoff_reviews", ["decision"], unique=False
    )
    op.create_index(
        op.f("ix_live_handoff_reviews_instance_id"),
        "live_handoff_reviews",
        ["instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_live_handoff_reviews_source_record_id"),
        "live_handoff_reviews",
        ["source_record_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_live_handoff_reviews_unit_id"), "live_handoff_reviews", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_live_handoff_reviews_user_id"), "live_handoff_reviews", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_live_handoff_reviews_workspace_id"),
        "live_handoff_reviews",
        ["workspace_id"],
        unique=False,
    )
    op.drop_index(op.f("idx_optimization_tasks_status"), table_name="optimization_tasks")
    op.create_index(
        op.f("ix_paper_equity_snapshots_instance_id"),
        "paper_equity_snapshots",
        ["instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_equity_snapshots_observed_at"),
        "paper_equity_snapshots",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_equity_snapshots_unit_id"),
        "paper_equity_snapshots",
        ["unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_equity_snapshots_user_id"),
        "paper_equity_snapshots",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_equity_snapshots_workspace_id"),
        "paper_equity_snapshots",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_review_reports_instance_id"),
        "paper_review_reports",
        ["instance_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_review_reports_source_record_id"),
        "paper_review_reports",
        ["source_record_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_paper_review_reports_status"), "paper_review_reports", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_paper_review_reports_unit_id"), "paper_review_reports", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_review_reports_user_id"), "paper_review_reports", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_review_reports_workspace_id"),
        "paper_review_reports",
        ["workspace_id"],
        unique=False,
    )
    op.drop_index(
        op.f("idx_paper_trading_orders_account_status"), table_name="paper_trading_orders"
    )
    op.create_index(
        op.f("ix_research_pipeline_events_iteration"),
        "research_pipeline_events",
        ["iteration"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_pipeline_events_mandate_id"),
        "research_pipeline_events",
        ["mandate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_pipeline_events_stage"),
        "research_pipeline_events",
        ["stage"],
        unique=False,
    )
    op.create_index(
        op.f("ix_research_pipeline_events_status"),
        "research_pipeline_events",
        ["status"],
        unique=False,
    )
    op.create_index(op.f("ix_risk_rules_instance_id"), "risk_rules", ["instance_id"], unique=False)
    op.create_index(op.f("ix_risk_rules_is_active"), "risk_rules", ["is_active"], unique=False)
    op.create_index(op.f("ix_risk_rules_rule_type"), "risk_rules", ["rule_type"], unique=False)
    op.create_index(op.f("ix_risk_rules_unit_id"), "risk_rules", ["unit_id"], unique=False)
    op.create_index(op.f("ix_risk_rules_user_id"), "risk_rules", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_risk_rules_workspace_id"), "risk_rules", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risk_rules_workspace_id"), table_name="risk_rules")
    op.drop_index(op.f("ix_risk_rules_user_id"), table_name="risk_rules")
    op.drop_index(op.f("ix_risk_rules_unit_id"), table_name="risk_rules")
    op.drop_index(op.f("ix_risk_rules_rule_type"), table_name="risk_rules")
    op.drop_index(op.f("ix_risk_rules_is_active"), table_name="risk_rules")
    op.drop_index(op.f("ix_risk_rules_instance_id"), table_name="risk_rules")
    op.drop_index(op.f("ix_research_pipeline_events_status"), table_name="research_pipeline_events")
    op.drop_index(op.f("ix_research_pipeline_events_stage"), table_name="research_pipeline_events")
    op.drop_index(
        op.f("ix_research_pipeline_events_mandate_id"), table_name="research_pipeline_events"
    )
    op.drop_index(
        op.f("ix_research_pipeline_events_iteration"), table_name="research_pipeline_events"
    )
    op.create_index(
        op.f("idx_paper_trading_orders_account_status"),
        "paper_trading_orders",
        ["account_id", "status"],
        unique=False,
    )
    op.drop_index(op.f("ix_paper_review_reports_workspace_id"), table_name="paper_review_reports")
    op.drop_index(op.f("ix_paper_review_reports_user_id"), table_name="paper_review_reports")
    op.drop_index(op.f("ix_paper_review_reports_unit_id"), table_name="paper_review_reports")
    op.drop_index(op.f("ix_paper_review_reports_status"), table_name="paper_review_reports")
    op.drop_index(
        op.f("ix_paper_review_reports_source_record_id"), table_name="paper_review_reports"
    )
    op.drop_index(op.f("ix_paper_review_reports_instance_id"), table_name="paper_review_reports")
    op.drop_index(
        op.f("ix_paper_equity_snapshots_workspace_id"), table_name="paper_equity_snapshots"
    )
    op.drop_index(op.f("ix_paper_equity_snapshots_user_id"), table_name="paper_equity_snapshots")
    op.drop_index(op.f("ix_paper_equity_snapshots_unit_id"), table_name="paper_equity_snapshots")
    op.drop_index(
        op.f("ix_paper_equity_snapshots_observed_at"), table_name="paper_equity_snapshots"
    )
    op.drop_index(
        op.f("ix_paper_equity_snapshots_instance_id"), table_name="paper_equity_snapshots"
    )
    op.create_index(
        op.f("idx_optimization_tasks_status"), "optimization_tasks", ["status"], unique=False
    )
    op.drop_index(op.f("ix_live_handoff_reviews_workspace_id"), table_name="live_handoff_reviews")
    op.drop_index(op.f("ix_live_handoff_reviews_user_id"), table_name="live_handoff_reviews")
    op.drop_index(op.f("ix_live_handoff_reviews_unit_id"), table_name="live_handoff_reviews")
    op.drop_index(
        op.f("ix_live_handoff_reviews_source_record_id"), table_name="live_handoff_reviews"
    )
    op.drop_index(op.f("ix_live_handoff_reviews_instance_id"), table_name="live_handoff_reviews")
    op.drop_index(op.f("ix_live_handoff_reviews_decision"), table_name="live_handoff_reviews")
    if _is_sqlite():
        with op.batch_alter_table("chat_messages") as batch_op:
            batch_op.drop_column("metadata")
    else:
        op.drop_column("chat_messages", "metadata")
    if _is_sqlite():
        with op.batch_alter_table("chat_conversations") as batch_op:
            batch_op.alter_column(
                "knowledge_base_id", existing_type=sa.VARCHAR(length=36), nullable=False
            )
    else:
        op.alter_column(
            "chat_conversations",
            "knowledge_base_id",
            existing_type=sa.VARCHAR(length=36),
            nullable=False,
        )
    op.create_index(
        op.f("idx_backtest_tasks_version_status_created_at"),
        "backtest_tasks",
        ["strategy_version_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_backtest_tasks_user_status"),
        "backtest_tasks",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("idx_backtest_tasks_user_created_at"),
        "backtest_tasks",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("idx_backtest_tasks_status"), "backtest_tasks", ["status"], unique=False)
    if _is_sqlite():
        with op.batch_alter_table("alerts") as batch_op:
            batch_op.drop_constraint("fk_alerts_workspace_id_workspaces", type_="foreignkey")
            batch_op.drop_constraint("fk_alerts_unit_id_strategy_units", type_="foreignkey")
    else:
        op.drop_constraint("fk_alerts_workspace_id_workspaces", "alerts", type_="foreignkey")
        op.drop_constraint("fk_alerts_unit_id_strategy_units", "alerts", type_="foreignkey")
    op.drop_index(op.f("ix_alerts_workspace_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_unit_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_instance_id"), table_name="alerts")
    op.drop_index(op.f("ix_ak_task_executions_airflow_run_id"), table_name="ak_task_executions")
    op.drop_index(op.f("ix_ak_task_executions_airflow_dag_id"), table_name="ak_task_executions")
    if _is_sqlite():
        with op.batch_alter_table("ak_task_executions") as batch_op:
            batch_op.drop_column("airflow_task_id")
            batch_op.drop_column("airflow_run_id")
            batch_op.drop_column("airflow_dag_id")
    else:
        op.drop_column("ak_task_executions", "airflow_task_id")
        op.drop_column("ak_task_executions", "airflow_run_id")
        op.drop_column("ak_task_executions", "airflow_dag_id")
    op.drop_index(
        op.f("ix_ai_strategy_research_versions_workspace_id"),
        table_name="ai_strategy_research_versions",
    )
    op.drop_index(
        op.f("ix_ai_strategy_research_versions_user_id"), table_name="ai_strategy_research_versions"
    )
    op.drop_index(
        op.f("ix_ai_strategy_research_versions_unit_id"), table_name="ai_strategy_research_versions"
    )
    op.drop_index(
        op.f("ix_ai_strategy_research_versions_strategy_id"),
        table_name="ai_strategy_research_versions",
    )
    op.drop_index(
        op.f("ix_ai_strategy_research_versions_quality_gate_status"),
        table_name="ai_strategy_research_versions",
    )
    op.drop_index(
        op.f("ix_ai_strategy_research_versions_mandate_id"),
        table_name="ai_strategy_research_versions",
    )
    op.drop_index(
        op.f("ix_ai_strategy_research_versions_backtest_task_id"),
        table_name="ai_strategy_research_versions",
    )
    op.drop_index(
        op.f("ix_ai_strategy_research_version_comparisons_user_id"),
        table_name="ai_strategy_research_version_comparisons",
    )
    op.drop_index(
        op.f("ix_ai_strategy_research_version_comparisons_right_version_id"),
        table_name="ai_strategy_research_version_comparisons",
    )
    op.drop_index(
        op.f("ix_ai_strategy_research_version_comparisons_left_version_id"),
        table_name="ai_strategy_research_version_comparisons",
    )
    op.drop_index(
        op.f("ix_ai_strategy_research_version_comparisons_created_at"),
        table_name="ai_strategy_research_version_comparisons",
    )
    op.drop_index(op.f("ix_strategy_scores_backtest_id"), table_name="strategy_scores")
    op.drop_table("strategy_scores")
    op.drop_index(op.f("ix_overfitting_results_user_id"), table_name="overfitting_results")
    op.drop_index(op.f("ix_overfitting_results_task_id"), table_name="overfitting_results")
    op.drop_index(op.f("ix_overfitting_results_backtest_id"), table_name="overfitting_results")
    op.drop_table("overfitting_results")
    op.drop_index(op.f("ix_news_analyses_owner_id"), table_name="news_analyses")
    op.drop_index(op.f("ix_news_analyses_article_id"), table_name="news_analyses")
    op.drop_table("news_analyses")
    op.drop_index(
        op.f("ix_portfolio_ledger_transactions_trade_type"),
        table_name="portfolio_ledger_transactions",
    )
    op.drop_index(
        op.f("ix_portfolio_ledger_transactions_trade_date"),
        table_name="portfolio_ledger_transactions",
    )
    op.drop_index(
        op.f("ix_portfolio_ledger_transactions_portfolio_id"),
        table_name="portfolio_ledger_transactions",
    )
    op.drop_table("portfolio_ledger_transactions")
    op.drop_index(
        op.f("ix_portfolio_ledger_snapshots_snapshot_date"), table_name="portfolio_ledger_snapshots"
    )
    op.drop_index(
        op.f("ix_portfolio_ledger_snapshots_portfolio_id"), table_name="portfolio_ledger_snapshots"
    )
    op.drop_table("portfolio_ledger_snapshots")
    op.drop_index(
        op.f("ix_portfolio_ledger_imports_portfolio_id"), table_name="portfolio_ledger_imports"
    )
    op.drop_index(
        op.f("ix_portfolio_ledger_imports_idempotency_key"), table_name="portfolio_ledger_imports"
    )
    op.drop_table("portfolio_ledger_imports")
    op.drop_index(op.f("ix_news_articles_source_id"), table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_owner_id"), table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_cluster_id"), table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_canonical_url"), table_name="news_articles")
    op.drop_table("news_articles")
    op.drop_index(op.f("ix_dg_quality_rules_endpoint_id"), table_name="dg_quality_rules")
    op.drop_table("dg_quality_rules")
    op.drop_index(op.f("ix_dg_ingest_jobs_idempotency_key"), table_name="dg_ingest_jobs")
    op.drop_index(op.f("ix_dg_ingest_jobs_endpoint_id"), table_name="dg_ingest_jobs")
    op.drop_table("dg_ingest_jobs")
    op.drop_index(op.f("ix_dg_endpoint_params_endpoint_id"), table_name="dg_endpoint_params")
    op.drop_table("dg_endpoint_params")
    op.drop_index(op.f("ix_portfolio_ledgers_owner_id"), table_name="portfolio_ledgers")
    op.drop_table("portfolio_ledgers")
    op.drop_index(op.f("ix_news_sources_owner_id"), table_name="news_sources")
    op.drop_table("news_sources")
    op.drop_index(op.f("ix_dg_endpoints_provider_id"), table_name="dg_endpoints")
    op.drop_index(op.f("ix_dg_endpoints_legacy_interface_name"), table_name="dg_endpoints")
    op.drop_index(op.f("ix_dg_endpoints_endpoint_name"), table_name="dg_endpoints")
    op.drop_index(op.f("ix_dg_endpoints_category"), table_name="dg_endpoints")
    op.drop_table("dg_endpoints")
    op.drop_index("ix_audit_user_timestamp", table_name="audit_records")
    op.drop_index("ix_audit_server_timestamp", table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_user_id"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_session_id"), table_name="audit_records")
    op.drop_index(op.f("ix_audit_records_event_type"), table_name="audit_records")
    op.drop_table("audit_records")
    op.drop_index(op.f("ix_strategy_explanations_code_hash"), table_name="strategy_explanations")
    op.drop_table("strategy_explanations")
    op.drop_index(op.f("ix_dg_providers_provider_id"), table_name="dg_providers")
    op.drop_index(op.f("ix_dg_providers_category"), table_name="dg_providers")
    op.drop_table("dg_providers")
    op.drop_index(
        op.f("ix_broker_connection_profiles_runtime_gateway_key"),
        table_name="broker_connection_profiles",
    )
    op.drop_index("ix_broker_connection_profiles_enabled", table_name="broker_connection_profiles")
    op.drop_index(
        op.f("ix_broker_connection_profiles_created_by"), table_name="broker_connection_profiles"
    )
    op.drop_index(
        op.f("ix_broker_connection_profiles_broker_id"), table_name="broker_connection_profiles"
    )
    op.drop_table("broker_connection_profiles")
    # ### end Alembic commands ###
